# OTO Distribution CloudFormation Template
# Static website distribution with S3 bucket, CloudFront distribution, and Origin Access Control
#
# Example deployment:
# BUCKET_NAME="oto-distribution"
# DOMAIN_NAME="oto.faermanj.com"
# ZONE_ID="Z044981111XDI2RGQ2GM9"
# CERTIFICATE_ARN="arn:aws:acm:us-east-1:730335617563:certificate/777043cb-290c-4e63-8a20-c970da31a8bf"
#
# aws cloudformation deploy \
#   --template-file oto-sam/distribution.cform.yaml \
#   --stack-name "oto-distribution-stack" \
#   --parameter-overrides \
#     DomainName=$DOMAIN_NAME \
#     HostedZoneId=$ZONE_ID \
#     CertificateArn=$CERTIFICATE_ARN \
#   --capabilities CAPABILITY_IAM

Description: "OTO static website distribution with S3 bucket, CloudFront distribution, and Origin Access Control"

Parameters:
  EnvId:
    Type: String
    Default: project
    Description: Environment identifier used to prefix exported outputs.

  DomainName:
    Type: String
    Description: Custom domain name for the CloudFront distribution (e.g., oto.example.com)
    AllowedPattern: ^[a-zA-Z0-9][a-zA-Z0-9-_.]*[a-zA-Z0-9]$

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for the domain

  CertificateArn:
    Type: String
    Description: ARN of the SSL certificate in ACM (must be in us-east-1 for CloudFront)
    AllowedPattern: ^arn:aws:acm:us-east-1:[0-9]{12}:certificate\/[a-f0-9-]+$
    ConstraintDescription: Must be a valid ACM certificate ARN in us-east-1 region

Resources:
  # S3 Bucket for static files
  DistributionBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Origin Access Control for CloudFront to access S3
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: !Sub "Origin Access Control for ${AWS::StackName}"

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Comment: !Sub "OTO static distribution for ${DomainName}"
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName:
              Fn::ImportValue: !Sub "${EnvId}-ResourcesBucketDomainName"
            OriginAccessControlId: !Ref OriginAccessControl
            S3OriginConfig:
              OriginAccessIdentity: ""
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only

  # Bucket Policy to allow CloudFront access via OAC
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: CloudFrontDistribution
    Properties:
      Bucket:
        Fn::ImportValue: !Sub "${EnvId}-ResourcesBucketName"
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource:
              Fn::Sub:
                - "arn:aws:s3:::${ResourcesBucketName}/*"
                - ResourcesBucketName:
                    Fn::ImportValue: !Sub "${EnvId}-ResourcesBucketName"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  # Route53 Record for custom domain
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  BucketDomainName:
    Description: Regional domain name of the S3 bucket
    Value: !GetAtt DistributionBucket.RegionalDomainName
    Export:
      Name: !Sub "${EnvId}-bucket-domain-name"

  DistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${EnvId}-distribution-id"

  DistributionDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${EnvId}-distribution-domain-name"

  WebsiteURL:
    Description: Website URL with custom domain
    Value: !Sub "https://${DomainName}"
    Export:
      Name: !Sub "${EnvId}-website-url"

  OriginAccessControlId:
    Description: Origin Access Control ID
    Value: !Ref OriginAccessControl
    Export:
      Name: !Sub "${EnvId}-oac-id"
